package io.mironov.sento;

public final class SentoFactory {
  public static Binding createBinding(final Class clazz) {
    throw new UnsupportedOperationException("This class will never be used in runtime. The real implementation will be generated by sento plugin.");
  }
}
